### ISSUE TITLE
AnomalyTransformer NaN values

### ISSUE THREAD

**Issue by rsulab** [Derposoft/crypto_pump_and_dump_with_deep_learning#13]
When i try train AT model i got 

![image](https://github.com/Derposoft/crypto_pump_and_dump_with_deep_learning/assets/58805372/fd4956ee-9bee-46d0-a794-9a95305a9e2f)

Is it normal?

**Comment by Derposoft** [comment]
Hey @rsulab, thanks for opening an issue. I'm not sure if this behavior is normal or not, but I certainly don't remember seeing nans during training so I'll look into it. I'll try to circle back on this over the weekend, so if you could answer a couple of questions for me that'd be great:
1. Do the accuracy/precision/recall/f1 seem to be improving?
2. Does the train loss switch from nan to a real value after running it for any longer (e.g., 20-30 epochs), or does it seem to be stuck at nan indefinitely?

**Comment by rsulab** [comment]
> Hey @rsulab, thanks for opening an issue. I'm not sure if this behavior is normal or not, but I certainly don't remember seeing nans during training so I'll look into it. I'll try to circle back on this over the weekend, so if you could answer a couple of questions for me that'd be great:
> 
> 1. Do the accuracy/precision/recall/f1 seem to be improving?
> 2. Does the train loss switch from nan to a real value after running it for any longer (e.g., 20-30 epochs), or does it seem to be stuck at nan indefinitely?

1. Do you mean make i some changes in code? No
2. I will check that

**Comment by rsulab** [comment]
> Hey @rsulab, thanks for opening an issue. I'm not sure if this behavior is normal or not, but I certainly don't remember seeing nans during training so I'll look into it. I'll try to circle back on this over the weekend, so if you could answer a couple of questions for me that'd be great:
> 
> 1. Do the accuracy/precision/recall/f1 seem to be improving?
> 2. Does the train loss switch from nan to a real value after running it for any longer (e.g., 20-30 epochs), or does it seem to be stuck at nan indefinitely?

![image](https://github.com/Derposoft/crypto_pump_and_dump_with_deep_learning/assets/58805372/ef95e013-82bf-40d3-aebb-929b7244e3bb)

**Comment by Derposoft** [comment]
@rsulab Sorry for the longer turnaround. This issue should be fixed now. Thanks for bringing it up! Let me know if it still persists.
