### ISSUE TITLE
Low F1  when using other dataset 

### ISSUE THREAD

**Issue by rsulab** [Derposoft/crypto_pump_and_dump_with_deep_learning#14]
I found strange behaviour

I trained model based on features_15S.csv.gz  

![image](https://github.com/Derposoft/crypto_pump_and_dump_with_deep_learning/assets/58805372/8f496804-c836-44e2-944e-40ecf97c6f09)

after that i add other pump data to this datatset
![image](https://github.com/Derposoft/crypto_pump_and_dump_with_deep_learning/assets/58805372/774abcd9-dd18-4a2c-9440-2b8ac0f50e9c)

Precision, Recall and  F1 dramatically changed

What is reason?

**Comment by Derposoft** [comment]
@rsulab Assuming that the only thing you have changed is the data (as you have implied), logic dictates that your new dataset is causing the difference. In general, you cannot guarantee that models trained on one dataset will perform just as well on another, unless they are drawn from the exact same distribution.

In this case, even if the data you've added is fundamentally similar, there is at least one clear difference: your epoch times imply you've nearly doubled the amount of data. Your metrics could be reflective of the fact that the model is predicting more confidently after training on the larger dataset.

To understand what that means, as well as how to interpret your metrics in particular, I think it would be helpful to first study the meaning of precision and recall, and to understand the significance of a precision-recall threshold. To me, your metrics suggest that you could try increasing that threshold. If that doesn't work, I would try tuning the hyperparameters of the model. Good luck :)

**Comment by rsulab** [comment]
Ok, thanks

I set precision-recall threshold to 0.9

![image](https://github.com/Derposoft/crypto_pump_and_dump_with_deep_learning/assets/58805372/89e580df-431e-43aa-86d3-5a9d47308265)

**Comment by rsulab** [comment]
> @rsulab Assuming that the only thing you have changed is the data (as you have implied), logic dictates that your new dataset is causing the difference. In general, you cannot guarantee that models trained on one dataset will perform just as well on another, unless they are drawn from the exact same distribution.
> 
> In this case, even if the data you've added is fundamentally similar, there is at least one clear difference: your epoch times imply you've nearly doubled the amount of data. Your metrics could be reflective of the fact that the model is predicting more confidently after training on the larger dataset.
> 
> To understand what that means, as well as how to interpret your metrics in particular, I think it would be helpful to first study the meaning of precision and recall, and to understand the significance of a precision-recall threshold. To me, your metrics suggest that you could try increasing that threshold. If that doesn't work, I would try tuning the hyperparameters of the model. Good luck :)

Full training result

![image](https://github.com/Derposoft/crypto_pump_and_dump_with_deep_learning/assets/58805372/c63f8d30-8116-4431-8340-215d84131615)

**Comment by Derposoft** [comment]
We can't help you tune your models. If you want to improve your metrics, I recommend rereading my last comment and playing around with more parameters. There are a lot of resources online (including but not limited to chatGPT) that can help you with that. Closing this issue now.
